apiVersion: v1
kind: Pod
metadata:
  name: dashapp
  labels:
    app: dashapp
spec:
  containers:
  - name: dashapp
    image: dashapp_skeleton:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"