# This is a format job. Pre-commit has a first-party GitHub action, so we use
name: Formatting (pre-commit)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "drydown_app/**"
      - "poetry.lock"
      - "Dockerfile"
      - ".github/workflows/format_enforcement.yml"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.12]
        poetry-version: [1.2.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # This is only needed when there are AWS resorces on pytest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_DEVELOPMENT }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Install dependencies
        run: |
            pip install pylint==2.15.2
            pip install pytest==7.1.3
            poetry config virtualenvs.create false
            poetry install

      - uses: pre-commit/action@v2.0.3
